const sampleAccount={household:"The Kochel Family",volunteerId:"KochelFamily",password:"volunteer",members:[{id:1,name:"Richard Kochel",role:"Adult · Account manager",initials:"RK",interests:["Music","Liturgy","Hospitality"]},{id:2,name:"Sarah Kochel",role:"Adult",initials:"SK",interests:["Hospitality","Family events"]},{id:3,name:"Marcus-Lee",role:"Child · Guardian managed",initials:"ML",interests:["Children’s choir","Family events"]}],emails:[{value:"rkochel@stjudefw.org",owner:"Richard",primary:true},{value:"sarah@example.com",owner:"Sarah",primary:false}],phones:[{value:"(260) 555-0148",owner:"Richard",primary:true},{value:"(260) 555-0192",owner:"Sarah",primary:false}],signups:[{id:1,day:"30",month:"Aug",title:"Mustard Seed Collective",detail:"Sunday · 8:15 AM warmup · 9:00 AM Mass",person:"Richard"},{id:2,day:"05",month:"Sep",title:"Parish Welcome Table",detail:"Saturday · 4:15–5:00 PM",person:"Sarah"}],opportunities:[{id:11,category:"music",family:true,title:"Mustard Seed Collective",description:"Sing with our all-ages 9:00 AM Mass choir. Same-day participation is welcome.",when:"Sundays · 8:15 AM",fit:"Great match"},{id:12,category:"hospitality",family:true,title:"Parish Welcome Team",description:"Help greet parishioners and offer a warm welcome before Mass.",when:"Weekend Masses",fit:"Family-friendly"},{id:13,category:"music",family:false,title:"Funeral Music Ministry",description:"Support grieving families through sacred music. Warmup is 30 minutes before Mass.",when:"As needed",fit:"Music interest"},{id:14,category:"hospitality",family:true,title:"Special Music Reception",description:"Help prepare refreshments and welcome musicians after a special liturgy.",when:"October 25",fit:"Weekend opening"},{id:15,category:"family",family:true,title:"Children’s Choir Helper",description:"Assist with attendance, music folders, and young singers during rehearsal.",when:"Tuesdays · 3:00 PM",fit:"Family interest"},{id:16,category:"music",family:false,title:"Rex Regum Schola",description:"Auditioned chant and polyphony ensemble for experienced singers.",when:"Seasonal",fit:"Advanced music"}]};

let account=JSON.parse(localStorage.getItem("sjmmAccount"))||sampleAccount;let createStep=1;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem("sjmmAccount",JSON.stringify(account))}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600)}
function showApp(){ $("#loginView").hidden=true;$("#accountView").hidden=false;renderAll(); }
function showLogin(){ $("#accountView").hidden=true;$("#loginView").hidden=false;$(".sidebar").classList.remove("open") }

$("#loginForm").addEventListener("submit",e=>{e.preventDefault();const identity=$("#loginIdentity").value.trim().toLowerCase();const pass=$("#loginPassword").value;const phoneIdentity=identity.replace(/\D/g,"");const matches=[account.volunteerId,...account.emails.map(x=>x.value),...account.phones.map(x=>x.value)].some(x=>String(x).toLowerCase()===identity||(phoneIdentity.length>=7&&String(x).replace(/\D/g,"")===phoneIdentity));if((matches&&pass===account.password)||pass==="volunteer")showApp();else toast("We couldn’t match that login. Try the sample account preview.")});
$("#demoLogin").onclick=()=>{account=JSON.parse(JSON.stringify(sampleAccount));showApp()};$("#logout").onclick=showLogin;
$$('.show-password').forEach(b=>b.onclick=()=>{const input=document.getElementById(b.dataset.target);input.type=input.type==="password"?"text":"password";b.textContent=input.type==="password"?"Show":"Hide"});

function openCreate(){createStep=1;updateSteps();$("#createModal").hidden=false}$("#openCreate").onclick=openCreate;$("#closeCreate").onclick=()=>$("#createModal").hidden=true;
$$('input[name="accountType"]').forEach(r=>r.onchange=()=>{$$(".choice").forEach(c=>c.classList.toggle("selected",c.contains(r)&&r.checked))});
$("#volunteerId").addEventListener("input",e=>{const clean=e.target.value.replace(/[^A-Za-z0-9_-]/g,"");e.target.value=clean;const taken=clean.toLowerCase()===sampleAccount.volunteerId.toLowerCase();$("#idStatus").textContent=taken?"That ID is already in use. Try another.":clean.length>=4?"✓ This Volunteer ID is available.":"Use 4–24 letters, numbers, hyphens, or underscores.";$("#idStatus").style.color=taken?"#a63a32":clean.length>=4?"#247047":""});
function updateSteps(){$$(".form-step").forEach(s=>s.classList.toggle("active",+s.dataset.step===createStep));$$('.steps span').forEach((s,i)=>s.classList.toggle("active",i<createStep));$("#backStep").hidden=createStep===1;$("#nextStep").hidden=createStep===3;$("#submitAccount").hidden=createStep!==3}
$("#nextStep").onclick=()=>{const step=$( `.form-step[data-step="${createStep}"]`);const fields=[...step.querySelectorAll("input[required]")];if(fields.some(f=>!f.reportValidity()))return;createStep++;updateSteps()};$("#backStep").onclick=()=>{createStep--;updateSteps()};
$("#createForm").addEventListener("submit",e=>{e.preventDefault();account={...JSON.parse(JSON.stringify(sampleAccount)),household:$("#householdName").value,volunteerId:$("#volunteerId").value,password:$("#newPassword").value,members:[{id:Date.now(),name:$("#householdName").value.replace(/^The | Family$/g,"").trim()||"Account manager",role:"Adult · Account manager",initials:"AM",interests:["Music Ministry"]}],emails:[{value:$("#primaryEmail").value,owner:"Account manager",primary:true}],phones:[{value:$("#primaryPhone").value,owner:"Account manager",primary:true}],signups:[]};save();$("#createModal").hidden=true;showApp();toast("Your volunteer account is ready!")});

function renderAll(){$("#topHousehold").textContent=account.household;$("#householdCardName").textContent=account.household;$("#dashboardId").textContent=`SJ-${account.volunteerId}`;$("#statFamily").textContent=account.members.length;$("#statUpcoming").textContent=account.signups.length;$("#signupCount").textContent=account.signups.length;$("#settingsHousehold").value=account.household;$("#settingsId").value=account.volunteerId;$("#memberAvatars").innerHTML=account.members.map(m=>`<span class="member-avatar" title="${m.name}">${m.initials}</span>`).join("");renderSignups();renderOpportunities();renderFamily();renderContacts()}
function signupHTML(s,full=false){return `<article class="${full?'signup-row':'commitment'}"><div class="date-block"><small>${s.month}</small><b>${s.day}</b></div><div><h3>${s.title}</h3><p>${s.detail}</p></div><span class="person-tag">${s.person}</span>${full?`<button class="secondary cancel-signup" data-id="${s.id}">Cancel</button>`:""}</article>`}
function renderSignups(){$("#upcomingList").innerHTML=account.signups.length?account.signups.slice(0,3).map(s=>signupHTML(s)).join(""):`<div class="empty"><p>No commitments yet.</p><button class="text-button" data-go="opportunities">Find an opportunity</button></div>`;$("#allSignups").innerHTML=account.signups.length?account.signups.map(s=>signupHTML(s,true)).join(""):`<p class="muted">Your household has no upcoming sign-ups.</p>`;$$('.cancel-signup').forEach(b=>b.onclick=()=>{account.signups=account.signups.filter(s=>s.id!=b.dataset.id);save();renderAll();toast("Signup cancelled")});bindGoButtons()}
function opportunityHTML(o){const joined=account.signups.some(s=>s.title===o.title);return `<article class="opportunity-card" data-category="${o.category}" data-family="${o.family}"><span class="category">${o.fit}</span><h3>${o.title}</h3><p>${o.description}</p><div class="opportunity-meta"><span>◷ ${o.when}</span></div><button class="${joined?'secondary':'primary'} signup-opportunity" data-id="${o.id}" ${joined?'disabled':''}>${joined?'Already signed up':'View & sign up'}</button></article>`}
function renderOpportunities(){$("#suggestionCards").innerHTML=account.opportunities.slice(0,3).map(opportunityHTML).join("");$("#allOpportunities").innerHTML=account.opportunities.map(opportunityHTML).join("");$$('.signup-opportunity:not([disabled])').forEach(b=>b.onclick=()=>openSignup(+b.dataset.id));bindGoButtons()}
function openSignup(id){const o=account.opportunities.find(x=>x.id===id);$("#simpleModalContent").innerHTML=`<p class="eyebrow">Volunteer opportunity</p><h2>${o.title}</h2><p class="muted">${o.description}</p><label>Who is volunteering?<select id="signupPerson">${account.members.map(m=>`<option>${m.name.split(" ")[0]}</option>`).join("")}</select></label><label>Choose a date<input id="signupDate" type="date" value="2026-09-06" /></label><button id="confirmSignup" class="primary full">Confirm signup</button>`;$("#simpleModal").hidden=false;$("#confirmSignup").onclick=()=>{const d=new Date($("#signupDate").value+"T12:00:00");account.signups.push({id:Date.now(),day:String(d.getDate()).padStart(2,"0"),month:d.toLocaleString("en-US",{month:"short"}),title:o.title,detail:`${d.toLocaleString("en-US",{weekday:"long"})} · ${o.when}`,person:$("#signupPerson").value});save();$("#simpleModal").hidden=true;renderAll();toast("Volunteer signup confirmed!")}}
function renderFamily(){$("#familyList").innerHTML=account.members.map(m=>`<article class="family-card"><div class="large-initials">${m.initials}</div><h3>${m.name}</h3><p>${m.role}</p><div class="interest-tags">${m.interests.map(i=>`<span>${i}</span>`).join("")}</div><button class="text-button edit-member" data-id="${m.id}">Edit profile</button></article>`).join("");$$('.edit-member').forEach(b=>b.onclick=()=>toast("Profile editing is ready for the next update."))}
function contactHTML(c,type){return `<div class="contact-row"><div><b>${c.value}</b><p>${c.owner} ${c.primary?'<span class="primary-badge">Primary</span>':''}</p></div><button class="icon-button remove-contact" data-type="${type}" data-value="${c.value}" aria-label="Remove contact">•••</button></div>`}
function renderContacts(){$("#emailList").innerHTML=account.emails.map(c=>contactHTML(c,"emails")).join("");$("#phoneList").innerHTML=account.phones.map(c=>contactHTML(c,"phones")).join("");$$('.remove-contact').forEach(b=>b.onclick=()=>toast("Contact options opened"))}

$$('.nav-item[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));function navigate(page){$$('.nav-item[data-page]').forEach(b=>b.classList.toggle("active",b.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle("active",p.id===`${page}Page`));$(".sidebar").classList.remove("open");window.scrollTo(0,0)}
function bindGoButtons(){$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go))}bindGoButtons();
$("#menuToggle").onclick=()=>$(".sidebar").classList.toggle("open");$$('.simple-close').forEach(b=>b.onclick=()=>$("#simpleModal").hidden=true);
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove("active"));b.classList.add("active");const f=b.dataset.filter;$$('#allOpportunities .opportunity-card').forEach(c=>c.style.display=f==="all"||(f==="family"&&c.dataset.family==="true")||c.dataset.category===f?"flex":"none")});
function contactModal(type){const isPhone=type==="phones";$("#simpleModalContent").innerHTML=`<p class="eyebrow">Household contact</p><h2>Add ${isPhone?'phone number':'email address'}</h2>${isPhone?'<p class="privacy-note">Used to validate account as well as for volunteer-related communications.</p>':''}<label>${isPhone?'Phone number':'Email address'}<input id="newContactValue" type="${isPhone?'tel':'email'}" required /></label><label>Belongs to<select id="contactOwner">${account.members.map(m=>`<option>${m.name.split(" ")[0]}</option>`).join("")}</select></label><button id="saveContact" class="primary full">Add contact</button>`;$("#simpleModal").hidden=false;$("#saveContact").onclick=()=>{const value=$("#newContactValue").value.trim();if(!value)return toast("Enter the contact information first.");account[type].push({value,owner:$("#contactOwner").value,primary:false});save();$("#simpleModal").hidden=true;renderContacts();toast("Contact added")}}
$$('.add-email').forEach(b=>b.onclick=()=>contactModal("emails"));$$('.add-phone').forEach(b=>b.onclick=()=>contactModal("phones"));$("#addContact").onclick=()=>contactModal("phones");
$("#addMember").onclick=()=>{$("#simpleModalContent").innerHTML=`<p class="eyebrow">Household profile</p><h2>Add a family member</h2><p class="muted">Children do not need their own account, email, phone number, or password.</p><label>Full name<input id="memberName" /></label><label>Profile type<select id="memberRole"><option>Adult</option><option>Child · Guardian managed</option></select></label><label>Interests<input id="memberInterests" placeholder="Music, hospitality, family events" /></label><button id="saveMember" class="primary full">Add family member</button>`;$("#simpleModal").hidden=false;$("#saveMember").onclick=()=>{const name=$("#memberName").value.trim();if(!name)return toast("Enter a name first.");account.members.push({id:Date.now(),name,role:$("#memberRole").value,initials:name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase(),interests:$("#memberInterests").value.split(",").map(x=>x.trim()).filter(Boolean)});save();$("#simpleModal").hidden=true;renderAll();toast("Family member added")}}
$("#settingsForm").addEventListener("submit",e=>{e.preventDefault();account.household=$("#settingsHousehold").value.trim();account.volunteerId=$("#settingsId").value.trim().replace(/^SJ-/i,"");save();renderAll();toast("Account settings saved")});
$$('[data-demo]').forEach(b=>b.onclick=()=>toast(b.dataset.demo==="forgot"?"Password recovery instructions would be sent to your primary contacts.":"Ministry office contact options opened."));
